### ISSUE TITLE
footprint.felixtsu.gitpress.org redirected to footprint.felix.gitpress.org

### ISSUE THREAD

**Issue by felixtsu** [75team/gitpress#11]
footprint.felixtsu.gitpress.org redirected to footprint.felix.gitpress.org

FelixTSUs-MacBook-Pro:footprint felix$ curl -i footprint.felixtsu.gitpress.org
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Wed, 25 Jun 2014 09:15:07 GMT
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: thinkjs-0.5.5
Location: //footprint.felix.gitpress.org/

**Comment by akira-cn** [comment]
没有发现这个问题啊？
